# Generated by Django 3.2.5 on 2021-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Пользователь'),
        ),
    ]
