# Generated by Django 3.2.5 on 2021-08-12 18:14

import aments_shop.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=250, verbose_name='Получатель')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('location', models.CharField(max_length=250, verbose_name='Дом, кв')),
                ('zip', models.CharField(max_length=25, verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Вес')),
                ('material', models.CharField(choices=[('STEEL', 'Сталь'), ('IRON', 'Железо'), ('ALUMINIUM', 'Алюминий'), ('CAST_IRON', 'Чугун'), ('POLYESTER', 'Полиэстер'), ('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG')], default='PLA', max_length=25, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'characteristic',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('preview', models.ImageField(upload_to='media/post_previews/', verbose_name='Превью')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 18, 14, 54, 628541), verbose_name='Дата публикации')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('TOMATO', 'Томатный'), ('GREEN', 'Зеленый'), ('AQUA', 'Аква'), ('VIOLET', 'Фиолетовый'), ('WHITE', 'Белый'), ('BLACK', 'Нигерский'), ('DEFAULT', 'По умолчанию')], default='DEFAULT', max_length=25, verbose_name='Цвета')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('characteristics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aments_shop.characteristic', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
                'db_table': 'rating_star',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тег')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/users_photos/'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.product', verbose_name='Продукт')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.ratingstar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Отзыв')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aments_shop.productreview', verbose_name='Родительский отзыв')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв к продукту',
                'verbose_name_plural': 'Отзывы к продукту',
                'db_table': 'product_review',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=aments_shop.models.image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.post', verbose_name='Пост')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='aments_shop.Tag', verbose_name='теги'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 18, 14, 54, 627611), verbose_name='Дата заказа')),
                ('count', models.SmallIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('IN_PROCESSING', 'В обработке'), ('ACCEPTED', 'Принята'), ('PREPARED_FOR_SHIPMENT', 'Подготовлено к отправке'), ('SENT', 'Отправлено'), ('DELIVERED', 'Доставлено'), ('COMPLETED', 'Завершен')], default='IN_PROCESSING', max_length=25, verbose_name='Статус')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aments_shop.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aments_shop.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'db_table': 'customer',
            },
        ),
    ]
