# Generated by Django 3.2.5 on 2021-08-12 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0004_auto_20210812_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreview',
            options={'verbose_name': 'Отзыв к посту', 'verbose_name_plural': 'Отзывы к посту'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 18, 17, 24, 739412), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 18, 17, 24, 740333), verbose_name='Дата публикации'),
        ),
        migrations.AlterModelTable(
            name='postreview',
            table='post_reviews',
        ),
    ]
