# Generated by Django 3.2.5 on 2021-08-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0010_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, unique=True, verbose_name='Скидка в %')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'product_sales',
            },
        ),
        migrations.RenameModel(
            old_name='ProjectAnalytics',
            new_name='ProductAnalytics',
        ),
        migrations.AlterModelOptions(
            name='productanalytics',
            options={'verbose_name': 'Аналитика', 'verbose_name_plural': 'Аналитика'},
        ),
    ]
