# Generated by Django 3.2.5 on 2021-08-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0011_auto_20210820_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aments_shop.productsales'),
        ),
    ]
