# Generated by Django 3.2.5 on 2021-08-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0013_auto_20210824_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productanalytics',
            options={'ordering': ('views',), 'verbose_name': 'Аналитика продукта', 'verbose_name_plural': 'Аналитика продуктов'},
        ),
        migrations.AlterModelTable(
            name='productanalytics',
            table='product_analytics',
        ),
        migrations.CreateModel(
            name='CategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0, verbose_name='Посещения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aments_shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аналитика категории',
                'verbose_name_plural': 'Аналитика категорий',
                'db_table': 'category_analytics',
                'ordering': ('visits',),
            },
        ),
    ]
