# Generated by Django 3.2.5 on 2021-08-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0014_auto_20210824_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAnalytics',
        ),
    ]
