# Generated by Django 3.2.5 on 2021-09-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0016_auto_20210826_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='productanalytics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='aments_shop.product', unique=True, verbose_name='Продукт'),
        ),
    ]
