# Generated by Django 3.2.5 on 2021-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0017_auto_20210903_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
