# Generated by Django 3.2.5 on 2021-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0018_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
