# Generated by Django 3.2.5 on 2021-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0019_auto_20210917_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
