# Generated by Django 3.2.5 on 2021-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0021_postreview_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
