# Generated by Django 3.2.5 on 2021-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aments_shop', '0023_auto_20210919_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
